### ISSUE TITLE
Is it possible to import custom instruments from Starbound?

### ISSUE THREAD

**Issue by steampunko** [iChun/Clef#9]
I was looking around and I noticed you literally just took the instruments from starbound and placed them in a .cia file. So I tried messing around and see if I could copy some instrument files from a mod and place them directly into the file, but it seems I'm mistaken...

**Comment by iChun** [comment]
You can. You need to unarchive the file if it's not a zip file and rezip it
and put it in. I've had it work with a few mods that come in zip format but
I've not tried other mods. I recall there being a bug causing mod
instruments not to load but I don't remember if I fixed it. I'll have to
look at it again sometime in the future.

**Comment by steampunko** [comment]
Do I just zip the unpacked content.pak contents?
Edit: I think I figured out how to get the packs set up, but it still doesn't work. The instruments do not show up in the creative tab.

**Comment by iChun** [comment]
Yes, somewhat. I don't remember the steps and I'm not at a computer now.
Unpack it and put it in a zip file with the same file structure and it
should try and load

**Comment by steampunko** [comment]
I've set it up I believe properly and now there are no instruments
![2017-12-27_13 39 25](https://user-images.githubusercontent.com/16859299/34394013-7c28e61c-eb0b-11e7-952c-a7206c62811b.png)
Well I mean there are a few that the server recognizes but almost all of the instruments vanish

**Comment by iChun** [comment]
Yeeeaaaah that's the bug I need to fix. I think if you remove the JSON file
it should be fine... I think.

**Comment by steampunko** [comment]
Which JSON do I remove?

**Comment by iChun** [comment]
The one in the root of the archive IIRC. Sorry I can't really help much
right now, I'm not near my main workspace and won't be for a while.

**Comment by steampunko** [comment]
I think the json you're talking about is actually a .cii file, and that's fine.

**Comment by iChun** [comment]
You could try it. I'm not too sure, it's been quite a while since I saw
Clef's code.

**Comment by steampunko** [comment]
I pretty much gave up trying to add them :S
